# Generated by Django 4.0.4 on 2022-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_Ambulance_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vehical_Number', models.CharField(max_length=20)),
                ('Vehical_Model', models.CharField(max_length=20)),
                ('Year_Made', models.CharField(max_length=10)),
                ('Driver_Name', models.CharField(max_length=100)),
                ('Driver_License', models.CharField(max_length=50)),
                ('Driver_Contact', models.CharField(max_length=15)),
                ('Vehical_Type', models.CharField(max_length=100)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_Appointment_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Token_Number', models.CharField(max_length=15)),
                ('Paitent_Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Referred_Doctor', models.CharField(max_length=100)),
                ('Visiting_Purpose', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=20)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_BirthRecord_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Child_Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=10)),
                ('Birth_Date', models.CharField(max_length=20)),
                ('Mother_Name', models.CharField(max_length=100)),
                ('Father_Name', models.CharField(max_length=100)),
                ('Report', models.CharField(max_length=1000)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_Covid_19_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paitent_Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Bed_Number', models.CharField(max_length=15)),
                ('Gaurdian_Name', models.CharField(max_length=100)),
                ('JOINED_DATE', models.CharField(max_length=10)),
                ('Todays_Report', models.CharField(max_length=1000)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_doctor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doctor_Name', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Availability', models.CharField(max_length=100)),
                ('Joined_Date', models.CharField(max_length=10)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_EmergencyWard_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(max_length=10)),
                ('Ward_Num', models.CharField(max_length=15)),
                ('Bed_Num', models.CharField(max_length=15)),
                ('JOINED_DATE', models.CharField(max_length=10)),
                ('Charges', models.CharField(max_length=15)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_IPD_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Joining_Date', models.CharField(max_length=10)),
                ('Paitent_Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone_Number', models.CharField(max_length=15)),
                ('Docter_Name', models.CharField(max_length=100)),
                ('Bed_Charges', models.CharField(max_length=15)),
                ('Payment', models.CharField(max_length=15)),
                ('Due_Payment', models.CharField(max_length=20)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_OPD_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paitent_Name', models.CharField(max_length=100)),
                ('Age', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Docter_Name', models.CharField(max_length=100)),
                ('Last_Visit', models.CharField(max_length=20)),
                ('Total_Visit', models.CharField(max_length=20)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_OperationTheater_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Number', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Contact_Number', models.CharField(max_length=15)),
                ('Operation_Name', models.CharField(max_length=50)),
                ('Operation_Type', models.CharField(max_length=50)),
                ('Assigned_Doctor', models.CharField(max_length=100)),
                ('OperationDate', models.CharField(max_length=10)),
                ('Applied_Charges', models.CharField(max_length=15)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_Pathology_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(max_length=10)),
                ('Test_Name', models.CharField(max_length=50)),
                ('Short_Name', models.CharField(max_length=10)),
                ('Test_Type', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('sub_Category', models.CharField(max_length=50)),
                ('Report_Days', models.IntegerField()),
                ('charge', models.CharField(max_length=15)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_Pharmacy_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PATIENT_NAME', models.CharField(max_length=100)),
                ('Docter_Name', models.CharField(max_length=100)),
                ('BILL_TOTAL', models.CharField(max_length=100)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_Radiology_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Patient_Id', models.CharField(max_length=10)),
                ('Test_Name', models.CharField(max_length=50)),
                ('Short_Name', models.CharField(max_length=10)),
                ('Test_Type', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=50)),
                ('sub_Category', models.CharField(max_length=50)),
                ('Report_Days', models.IntegerField()),
                ('charge', models.CharField(max_length=15)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='add_staff_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Id', models.CharField(max_length=20)),
                ('Staff_Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Joined_Date', models.CharField(max_length=10)),
                ('Attendance', models.CharField(max_length=50)),
                ('loger_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Appointment_form_submition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Your_Name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_time', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='contact_form_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='otp_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='registration_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
                ('profile', models.FileField(upload_to='profiles')),
                ('mobile_number', models.CharField(max_length=15)),
            ],
        ),
    ]
