# Generated by Django 5.1.2 on 2024-12-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_alter_registration_table_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_table',
            name='profile',
            field=models.FileField(upload_to='profiles'),
        ),
    ]
